export const types =  {

    REGISTER_REQUESTED: 'REGISTER_REQUESTED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',

    LOGIN_REQUESTED: 'LOGIN_REQUESTED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    LOGOUT_REQUESTED: 'LOGOUT_REQUESTED',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',

    GET_USERS_REQUESTED: 'GET_USERS_REQUESTED',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILED: 'GET_USERS_FAILED',

    TOKEN_FAILED: 'TOKEN_FAILED',
    TOKEN_SUCCESS: 'TOKEN_SUCCESS',

    RESET_SUCCESS: 'RESET_SUCCESS',
    RESET_FAILED:  'RESET_FAILED',

    SHOW_MESSAGE: 'SHOW_MESSAGE',
    SET_LOGIN_FORM: 'SET_LOGIN_FORM',
    SET_REGISTER_FORM: 'SET_REGISTER_FORM',

    CONFIRM_EMAIL_SUCCESS: 'CONFIRM_EMAIL_SUCCESS',
    CONFIRM_EMAIL_FAILED: 'CONFIRM_EMAIL_FAILED',

    CHANGE_SUCCESS: 'CHANGE_SUCCESS',
    CHANGE_FAILED: 'CHANGE_FAILED',

    SET_CHANGE_FORM: 'SET_CHANGE_FORM',

    CODE_ADMIN_SUCCESS: 'CODE_ADMIN_SUCCESS',
    CODE_ADMIN_FAILED: 'CODE_ADMIN_FAILED',

    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_FAILED: ' UPDATE_FAILED',

    SHARE_USER: 'SHARE_USER',

    CREATE_SUCCESS: 'CREATE_SUCCESS',

    SHARE_PAYMENT_RESSOURCE: 'SHARE_PAYMENT_RESSOURCE',

    SHARE_STUDENT_USER: 'SHARE_STUDENT_USER',
    SHARE_PARENT_USER: 'SHARE_PARENT_USER',
    SHARE_ADMIN_USER: 'SHARE_ADMIN_USER',
    SHARE_TUTOR_USER: 'SHARE_TUTOR_USER',
    SHARE_TUTOR_SPECIALITIES: 'SHARE_TUTOR_SPECIALITIES',
    SHARE_COURSES: 'SHARE_COURSES',
    SHARE_HORAIRE_USER: 'SHARE_HORAIRE_USER',

    MEDIA_ID: 'MEDIA_ID',

    SHARE_TUTOR_FOR_STUDENT: 'SHARE_TUTOR_FOR_STUDENT',

    SHARE_MEETING_PROGRAMM: 'SHARE_MEETING_PROGRAMM',
    SHARE_MEET_TUTOR: 'SHARE_MEET_TUTOR',

    SHARE_CHAPTER: 'SHARE_CHAPTER',

    

    
};