export const types =  {

    REGISTER_REQUESTED: 'REGISTER_REQUESTED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILED: 'REGISTER_FAILED',

    LOGIN_REQUESTED: 'LOGIN_REQUESTED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',

    LOGOUT_REQUESTED: 'LOGOUT_REQUESTED',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',

    GET_USERS_REQUESTED: 'GET_USERS_REQUESTED',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILED: 'GET_USERS_FAILED',

    TOKEN_FAILED: 'TOKEN_FAILED',
    TOKEN_SUCCESS: 'TOKEN_SUCCESS',

    RESET_SUCCESS: 'RESET_SUCCESS',
    RESET_FAILED:  'RESET_FAILED',
};